[package]
name = "name-all-the-numbers"
version = "0.1.0"
authors = ["IrregularPersona"]
entrypoint = "lib.typ"
license = "GPL-3.0-only"
repository = "https://github.com/IrregularPersona/name-all-the-numbers"
description = "Get the names of integers in Typst in any language."
